version: '3'
volumes:
  lb_kc_mysql:
      driver: local
services:
  mysql:
      image: mysql:5.7.29
      volumes:
        - lb_kc_mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: keycloak
  keycloak:
      image: jboss/keycloak:9.0.0
      environment:
        DB_VENDOR: mysql
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: keycloak
        JDBC_PARAMS: "connectTimeout=30000&useSSL=false"
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      depends_on:
        - mysql
  lb:
      image: haproxy:2.1.3
      ports:
        - 80:8080
      links:
        - keycloak
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
