version: '3.2'
volumes:
  mysql_data:
      driver: local
services:
  mysql:
      image: mysql:5.7.29
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: keycloak
  keycloak:
      image: secondriver/kc9:preview
      environment:
        DB_VENDOR: mysql
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: keycloak
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        JDBC_PARAMS: "connectTimeout=30000&useSSL=false"
        PROXY_ADDRESS_FORWARDING: "true"
      ports:
        - 8081:8080
      depends_on:
        - mysql
