version: '3.2'
volumes:
  mysql_data:
      driver: local
  kc_theme_data:
      driver: local
  kc_cert_data:
      driver: local
services:
  mysql:
      image: mysql:5.7.29
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: keycloak
  keycloak-node1:
      image: secondriver/kc9:preview.jdbc.tcp
      volumes:
        - kc_cert_data:/etc/x509
        - kc_theme_data:/opt/jboss/keycloak/themes
      environment:
        DB_VENDOR: mysql
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: keycloak
        JDBC_PARAMS: "connectTimeout=30000&useSSL=false"
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        PROXY_ADDRESS_FORWARDING: "true"
	JGROUPS_DISCOVERY_PROTOCOL: "JDBC_PING"
	JGROUPS_DISCOVERY_PROPERTIES: "datasource_jndi_name=java:jboss/datasources/KeycloakDS"
      ports:
        - 8081:8080
      depends_on:
        - mysql
  keycloak-node2:
      image: secondriver/kc9:preview.jdbc.tcp
      volumes:
        - kc_cert_data:/etc/x509
        - kc_theme_data:/opt/jboss/keycloak/themes
      environment:
        DB_VENDOR: mysql
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: keycloak
        JDBC_PARAMS: "connectTimeout=30000&useSSL=false"
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        PROXY_ADDRESS_FORWARDING: "true"
	JGROUPS_DISCOVERY_PROTOCOL: "JDBC_PING"
	JGROUPS_DISCOVERY_PROPERTIES: "datasource_jndi_name=java:jboss/datasources/KeycloakDS"
      ports:
        - 8082:8080
      depends_on:
        - mysql
